# ----------------------------------------------------------------------------------------------- #
# CONFIGURATION FILE
# ----------------------------------------------------------------------------------------------- #

# Sequencing units sheet
#  TSV file with sample name, sequencing lane, path to fastq forward, path to fastq reverse
units: configuration/units.tsv

# Sample information sheet.
#  Sample name must be equal to that in "units"
samples: configuration/samples.tsv

# Parameters for submitting jobs to cluster via qsub
cluster: configuration/cluster.yaml

# Prefix to temporary
# Some files -such as fastq- occupy a lot of space. To avoid space problems during the processing of the pipelines
# we can use the temporary scratch of hpcnfs or the scratch directory of each node.
# Just write the prefix-path where you want to put those files, or write '.' to have them in the workdir.
# By now just fastq files will be located in this folder
# IMPORTANT: if you have running multiple snakemake pipelines with the same tmp folder all the fastq files will be located togeter. Care with the sample names to not be repeated.
tmp: /hpcnfs/scratch/temporary/.atacmitji

# Reference files and parameters for reference genome and promoter definition
ref:
  # Genome used
  genome: mm10
  # ChrM name to remove it
  chrM_name: chrM
  # Determine the region corresponding to promoters around TSS
  promoter:
    # After TSS
    aTSS: 2500
    # Before TSS
    bTSS: 2500
  # Bowtie index for the alignment of the sample
  index: /hpcnfs/techunits/bioinformatics/refdata/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome
  # Bowtie index for the alignmed of the spike-in, if there is
  index_spike: /hpcnfs/data/DP/dm6/dm6
  # File required by computeGCbias from deeptools
  2bit: /hpcnfs/data/DP/Databases/mm10.2bit
  # Used in computeGCbias to ignore repetitive regions in the calculation
  rep_masker: /hpcnfs/data/DP/Databases/RepeatMasker_noRandom_mm10.bed
  # File required by bdg2bigwig from ucsc
  chr_sizes: /hpcnfs/data/DP/Databases/mm10.chrom.sizes
  # https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
  # 2304947926 --> mm9
  # 2308125349 --> mm10
  egenome_size: 2308125349


options:
  # split the BAM file into nucleosome-free regions and nucleosome regions using alignmentSieve from deeptools
  # also call peaks from the separated bamfiles separately usign genrich
  splitBam: False
  # pool replicates within peak calling with Genrich, only if peakcaller is set to "genrich": True or False
  genrich_pool: True
  ### THE FOLLOWING OPTIONS ARE NOT ENABLED YET, SO IF YOU SET THEM TO True IT WON'T HAPPEN ANYTHING.
  # get rid of reads mapping in the chrM (from the bamfiles): true or false. It will be read in bash
  rm_chrM: True  # not able yet
  # to downsample the bam files per groups
  downsample: False  # not able yet
  # perform trimming: false or true
  # if true go to params (at the end)
  # to set desired trimming parameters
  trimming: false


# Parameters for the software used
params:
  
  # Bowtie2 params
  bowtie2: 
    # https://www.protocols.io/view/cut-amp-tag-data-processing-and-analysis-tutorial-bjk2kkye.html
    global: "--local --very-sensitive --no-mixed --no-discordant --phred33"
    pe: "-I 10 -X 700"

  # Samblaster by default just mark duplicates but doesn't remove them. To remove pcr duplicates add --removeDups here.
  samblaster: "--removeDups"
  
  # Samtools params
  samtools:
    # Memory used by every core of samtools (GB). Be careful that 
    # memory x threads is not bigger than the amount of memory assigned to align rule
    memory: 2

  # Fastp params 
  fastp:
    se: "-Q -L"
    pe: "-Q -L --detect_adapter_for_pe"

  splitbam:
    # To split the bam using alignmentSieve from deeptools
    # Fragments below this length will be considered as nucleosome free regions
    # Fragments above this length will be considered as nucleosome regions
    nfr_length: 150 

  genrich: #https://github.com/jsh58/Genrich
    #path: "/hpcnfs/data/DP/amitjavila/software/Genrich/Genrich"
    atac_mode: "-j" # whether to use atac mode (-j) or normal mode "". one of "-j" or "". https://github.com/jsh58/Genrich#atac-seq-mode
    pe_or_se: "" # whether samples are PE o SE. It works only when options: genrich_merge: True
    unmatch: "-y -d 150" # whether to use unmatched reads.
    p_or_q: "p" #either "p" (for pvalue filtering) or "q" (for qvalue threshold)
    pqval: 5e-4 #q- or p- value that will be use as threshold (depends on p_or_q param)
    filt: "5" # minumum -log10(qvalue) value that will be use to filter peaks after peak calling
    chrM: "-e chrM" # to get rid of the reads mapping in the mitochondrial chromosome. either "-e chrM" or ""
    PRCdups: "" # to remove PCR duplicates; either "" or "-r". Default is "" since PCR dups are removed in the aligning step

  # Bam2bigwig params
  bam2bigwig:
    read_extension: 200
    other: "--binSize 50"
    

