# CONFIG FILE
# ===========

# Sequencing units sheet
#  TSV file with sample name, sequencing lane, path to fastq forward, path to fastq reverse
units: configuration/units.tsv

# Sample information sheet.
#  Sample name must be equal to that in "units"
samples: configuration/samples.tsv

# Parameters for submitting jobs to cluster via qsub
cluster: configuration/cluster.yaml

# Prefix to temporary
# Some files -such as fastq- occupy a lot of space. To avoid space problems during the processing of the pipelines
# we can use the temporary scratch of hpcnfs or the scratch directory of each node.
# Just write the prefix-path where you want to put those files, or write '.' to have them in the workdir.
# By now just fastq files will be located in this folder
# IMPORTANT: if you have running multiple snakemake pipelines with the same tmp folder all the fastq files will be located togeter. Care with the sample names to not be repeated.
tmp: /hpcnfs/scratch/temporary/.snakemake_atac_genrich

# perform trimming: false or true
# if true go to params (at the end)
# to set desired trimming parameters
trimming: false

# Parameters for the software used
params:

  # Bowtie params
  bowtie:
    global: "--chunkmbs 1024 -m 1 --best -S --no-unal -q"
    pe: "-I 10 -X 1000"

  samtools:
    # Memory used by every core of samtools (GB). Be careful that 
    # memory x threads is not bigger than the amount of memory assigned to align rule
    memory: 2

  fastp:
    se: "-t 1 -A -Q -L"
    pe: "-t 1 -A -Q -L"

  genrich:
    path: "/hpcnfs/data/DP/amitjavila/software/Genrich/Genrich"
    se: "-y -d 150"
    p_or_q: "p" #either "p" (for pvalue filtering) or "q" (for qvalue threshold)
    pqval: 0.0001 #q- or p- value that will be use as threshold (depends on p_or_q param)
    filt_peaks_pqval: "5" # minumum -log10(qvalue) value that will be use to filter peaks after peak calling

  # Macs2 params
  macs2:
    callpeak: "--keep-dup all -m 3 30"
    gsize: mm
    pvalue: 1e-5
    pvalue_broad: 1e-5
    # -log10 pvalue for peak filtering - corresponds to the 8th column of the narrowPeak file. Default 10.
    filt_peaks_pval: "10"

  # Bam2bigwig params
  bam2bigwig:
    read_extension: 200
    other: "--binSize 50"

# Determine the region corresponding to promoters around TSS
promoter:
  # After TSS
  aTSS: 2500
  # Before TSS
  bTSS: 2500

# Reference files and parameters for mm10 mouse genome version.
ref:
  # Bowtie index for the alignment of the sample
  index: /hpcnfs/techunits/bioinformatics/refdata/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex/genome
  # Bowtie index for the alignmed of the spike-in, if there is
  index_spike: /hpcnfs/data/DP/dm6/dm6
  # File required by computeGCbias from deeptools
  2bit: /hpcnfs/data/DP/Databases/mm10.2bit
  # Used in computeGCbias to ignore repetitive regions in the calculation
  rep_masker: /hpcnfs/data/DP/Databases/RepeatMasker_noRandom_mm10.bed
  # File required by bdg2bigwig from ucsc
  chr_sizes: /hpcnfs/data/DP/Databases/mm10.chrom.sizes
  # https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
  # 2304947926 --> mm9
  # 2308125349 --> mm10
  egenome_size: 2308125349

options:
  # Caller: one of "macs" or "genrich"
  peakcaller: "genrich"
  ### THE FOLLOWING OPTIONS ARE NOT ENABLED YET, SO IF YOU SET THEM TO True IT WON'T HAPPEN ANYTHING.
  # merge within peak calling with Genrich, only if peakcaller is set to "genrich": True or False
  genrich_merge: False
  # merge replicate samples with IDR when calling peaks with macs2: True or False
  idr_merge: False
  # get rid of reads mapping in the chrM: True or False.
  no_chrM: False
  # do downsample or not: True or False.
  downsample: False


  
  
