# CONFIG FILE
# ===========

# Sequencing units sheet
#  TSV file with sample name, sequencing lane, path to fastq forward, path to fastq reverse
units: configuration/units.tsv

# Sample information sheet.
#  Sample name must be equal to that in "units"
samples: configuration/samples.tsv

# Parameters for submitting jobs to cluster via qsub
cluster: configuration/cluster.yaml

# Parameters for the software used
params:

  # Bowtie params
  bowtie:
    global: "--chunkmbs 1024 -m 1 --best -S --no-unal -q"
    pe: "-I 10 -X 1000"

  # Fastp params
  fastp:
    se: "--stdin -t 1 -A -Q -L"
    pe: "-t 1 -A -Q -L"

  genrich:
    path: "/hpcnfs/data/DP/amitjavila/software/Genrich/Genrich"
    se: "-y -d 150"

  # Macs2 params
  macs2:
    callpeak: "--keep-dup all -m 3 30"
    gsize: mm
    pvalue: 1e-5
    pvalue_broad: 1e-5
    # -log10 pvalue for peak filtering - corresponds to the 8th column of the narrowPeak file. Default 10.
    filt_peaks_pval: "10"

  # Bam2bigwig params
  bam2bigwig:
    read_extension: 200
    other: "--binSize 50"

# Determine the region corresponding to promoters around TSS
promoter:
  # After TSS
  aTSS: 2500
  # Before TSS
  bTSS: 2500

# Reference files and parameters for mm10 mouse genome version.
ref:
  # Bowtie index for the alignment of the sample
  index: /hpcnfs/techunits/bioinformatics/refdata/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex/genome
  # Bowtie index for the alignmed of the spike-in, if there is
  index_spike: /hpcnfs/data/DP/dm6/dm6
  # File required by computeGCbias from deeptools
  2bit: /hpcnfs/data/DP/Databases/mm10.2bit
  # Used in computeGCbias to ignore repetitive regions in the calculation
  rep_masker: /hpcnfs/data/DP/Databases/RepeatMasker_noRandom_mm10.bed
  # File required by bdg2bigwig from ucsc
  chr_sizes: /hpcnfs/data/DP/Databases/mm10.chrom.sizes
  # https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
  # 2304947926 --> mm9
  # 2308125349 --> mm10
  egenome_size: 2308125349

options:
  # Caller: one of "macs" or "genrich"
  caller: "genrich"
  # get rid of reads mapping in the chrM: True or False.
  no_chrM: False
  # do downsample or not: True or False.
  downsample: False
  # merge replicate samples with IDR: True or False
  idr: False
  
